# Log body template patterns
# Patterns are applied in order - most specific patterns should come first
# Each pattern will replace matching text with its placeholder

patterns:
  # Timestamp patterns
  - name: apache_timestamp
    regex: '\[(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{2}\s+\d{2}:\d{2}:\d{2}\s+\d{4}\]'
    placeholder: '<TIMESTAMP>'
    description: 'Apache-style timestamps [Weekday Month DD HH:MM:SS YYYY]'

  - name: syslog_timestamp
    regex: '(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}'
    placeholder: '<TIMESTAMP>'
    description: 'Syslog timestamps (MMM DD HH:MM:SS)'

  - name: timestamp
    regex: '\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}'
    placeholder: '<TIMESTAMP>'
    description: 'ISO-like timestamps (YYYY/MM/DD HH:MM:SS)'
  
  # UUID patterns
  - name: uuid
    regex: '\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b'
    placeholder: '<UUID>'
    description: 'Standard UUID format'
  
  # Email patterns
  - name: email
    regex: '\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b'
    placeholder: '<EMAIL>'
    description: 'Email addresses'
  
  # URL patterns
  - name: url
    regex: 'https?://[^\s]+|\s(/[a-zA-Z0-9/_.-]+)'
    placeholder: ' <URL>'
    description: 'HTTP/HTTPS URLs and absolute paths'
  
  # Duration patterns
  - name: duration
    regex: '\d+(?:\.\d+)?(?:µs|ms|s|m|h)\b'
    placeholder: '<DURATION>'
    description: 'Time durations with units'
  
  # Size patterns
  - name: size
    regex: '\d+(?:\.\d+)?(?:B|KB|MB|GB)\b'
    placeholder: '<SIZE>'
    description: 'File/memory sizes with units'
  
  # IP address patterns
  - name: ip
    regex: '\[::1\]|\b(?:\d{1,3}\.){3}\d{1,3}\b'
    placeholder: '<IP>'
    description: 'IPv4 addresses and localhost IPv6'
  
  # Hexadecimal patterns (8+ chars)
  - name: hex
    regex: '\b[0-9a-f]{8,}\b'
    placeholder: '<HEX>'
    description: 'Long hexadecimal strings (8+ characters)'
  
  # Generic number patterns (applied last)
  - name: number
    regex: '\b\d+\b'
    placeholder: '<NUM>'
    description: 'Any numeric value'
